name: Expresiones en GitHub Actions
run-name: Runner - Expresiones en GitHub Actions
on:
    push
jobs:
    quiz-expresiones:
        runs-on: ubuntu-latest

        env: 
            QUIZ_NOMBRE: Ada Lovelace
            QUIZ_LENGUAJE: Python
            QUIZ_NUMERO: 42
            

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v4

            - name: Ejecutar quiz_expresiones.py
              run: python quiz_expresiones.py