name: Expresiones en GitHub Actions
run-name: Runner - Expresiones en GitHub Actions
on:
    push
jobs:
    quiz-expresiones:
        runs-on: ubuntu-latest

        env: 
            QUIZ_NOMBRE: Ada Lovelace
            QUIZ_LENGUAJE: Python
            QUIZ_NUMERO: 42
            QUIZ_ENTORNO: production
            QUIZ_FUNCION: true
            TEMP_INT_TO_HEXA: 26
            TEMP_HEXA_TO_INT: 0
            QUIZ_HEXADECIMAL: 0
            QUIZ_FLOAT: 3.14159
            TEMP_JSON: '{"nombre": "Ada Lovelace", "lenguaje"   : "Python", "numero": 100 }'
            QUIZ_FROMJSON_NUMERO: 0


            

        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v4

            - name: Convertir decimal a hexadecimal
              run: |
                  decimal=${{ env.TEMP_INT_TO_HEXA }}
                  hexadecimal=$(printf '%x' $decimal)
                  quiz_hexadecimal=$(printf '%d\n' "0x$hexadecimal")
                  echo "Decimal: $decimal"
                  echo "Hexadecimal: $hexadecimal"
                  echo "Decimal a Hexadecimal: $quiz_hexadecimal"
                  echo "QUIZ_HEXADECIMAL=$quiz_hexadecimal" >> $GITHUB_ENV

            - name: Extraer numero de JSON (fromJSON)
              run:  |
                  echo "QUIZ_FROMJSON_NUMERO=${{fromJson(env.TEMP_JSON).numero}}" >> $GITHUB_ENV

            - name: Ejecutar quiz_expresiones.py
              run: python quiz_expresiones.py